behaviors:
  simpleshooter:
    trainer_type: poca
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.04
        gamma: 0.99
        encoding_size: 128
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 1000
    summary_freq: 10000
    self_play:
      save_steps: 50000
      team_change: 500000
      swap_steps: 150000
      window: 100
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
# behaviors:
#   simpleshooter:
#     trainer_type: poca
#     hyperparameters:
#       batch_size: 2048
#       buffer_size: 20480
#       learning_rate: 0.0005
#       beta: 0.005
#       epsilon: 0.2
#       lambd: 0.95
#       num_epoch: 3
#       learning_rate_schedule: constant
#     network_settings:
#       normalize: false
#       hidden_units: 512
#       num_layers: 3
#       vis_encode_type: simple
#     reward_signals:
#       extrinsic:
#         gamma: 0.99
#         strength: 1.0
#       curiosity:
#         strength: 0.08
#         gamma: 0.99
#         encoding_size: 128
#     keep_checkpoints: 5
#     max_steps: 50000000
#     time_horizon: 1000
#     summary_freq: 10000
#     self_play:
#       save_steps: 50000
#       team_change: 500000
#       swap_steps: 200000
#       window: 100
#       play_against_latest_model_ratio: 0.5
#       initial_elo: 1200.0
    # trainer_type: poca
    # hyperparameters:
    #   batch_size: 512
    #   buffer_size: 2048
    #   learning_rate: 0.0001
    #   beta: 0.0005
    #   epsilon: 0.35
    #   lambd: 0.95
    #   num_epoch: 3
    #   learning_rate_schedule: constant
    # network_settings:
    #   normalize: false
    #   hidden_units: 128
    #   num_layers: 4
    #   vis_encode_type: simple
    # reward_signals:
    #   extrinsic:
    #     gamma: 0.99
    #     strength: 0.9
    # keep_checkpoints: 5
    # max_steps: 50000000
    # time_horizon: 1000
    # summary_freq: 10000
    # self_play:
    #   save_steps: 10000
    #   team_change: 40000
    #   swap_steps: 10000
    #   window: 50
    #   play_against_latest_model_ratio: 0.5
    #   initial_elo: 1200.0